import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from './theme';
import './globals.css';

import SdkInit from './SdkInit';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className='antialiased'>
        <ThemeProvider>
            <SdkInit />
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

